name: Cypress Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  RunCypress:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: yarn e2e:ci
        env: 
          CYPRESS_RECORD_KEY: ${{secrets.GITHUB_TOKEN}}
          PREVIEW_URL: ${{steps.waitFor200.outputs.url}}
    


