name: Cypress Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  runTestsAgainstPreview:
    name: Run Tests Against Preview URL
    runs-on: "ubuntu-latest"
    steps:
      - name: Capture Vercel preview URL
        id: waitFor200
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        id: runCypress
        with:
          record: true
          parallel: true
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          config: baseUrl=${{steps.waitFor200.outputs.url}}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
        if: ${{ steps.runCypress.outcome == 'success' }}

  automerge:
    runs-on: ubuntu-latest
    needs: runTestsAgainstPreview
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000
