name: Quality & Deploy

on:
  pull_request:
    branches: master

jobs:
  unitTests:
    uses: ./.github/workflows/unitTests.yml

  lostPixel: 
    uses: ./.github/workflows/visualRegression.yml

  runTestsAgainstPreview:
    uses: ./.github/workflows/uiTesting.yml

  automerge:
    runs-on: ubuntu-latest
    needs: [lostPixel, runTestsAgainstPreview]
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        if: ${{ github.ref != 'refs/heads/master' }}
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_RETRIES: 10
          MERGE_RETRY_SLEEP: 10000