name: Cypress Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  getPreviewUrl:
    runs-on: ubuntu-latest
    container: node:16.12.0-buster
    steps:
      - name: Waiting for 200 from the Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitFor200
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - run: echo ${{steps.waitFor200.outputs.url}} > previewUrl.txt
  runCypress:
    runs-on: ubuntu-latest
    container: cypress/browsers:node16.14.2-slim-chrome100-ff99-edge
    needs: waitFor200
    steps: 
    - name: Run Cypress Against Preview
      uses: actions/checkout@v3
    - run: export PREVIEW_URL=$(cat previewUrl.txt)
    - run: yarn e2e:ci


