name: Cypress Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  capture_vercel_preview_url:
    name: Capture Vercel preview URL
    runs-on: "ubuntu-latest"
    steps:
      - name: Get Preview Url
      - uses: aaimio/vercel-preview-url-action@v1
        id: vercel_preview_url
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env: 
          CYPRESS_RECORD_KEY: ${{secrets.GITHUB_TOKEN}}
          PREVIEW_URL: ${{ steps.vercel_preview_url.outputs.vercel_preview_url }}
      


