name: Cypress Tests

on:
  pull_request:
  push:
    branches: master

jobs:
  runTestsAgainstPreview:
    name: Run Tests Against Preview URL
    runs-on: "ubuntu-latest"
    steps:
      - name: Capture Vercel preview URL
        id: waitFor200
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
        run: echo "${{steps.waitFor200.outputs.url}}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v2
        run: echo "${{steps.waitFor200.outputs.url}}"
        with:
          command: npm run e2e:ci
          record: true
          parallel: true
          ci-build-id: '${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}'
          config: baseUrl=${{steps.waitFor200.outputs.url}}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      


