name: Run UI Tests

on:
  workflow_call:
  workflow_dispatch:
env:
  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
jobs:
  runUITesting:
    runs-on: ubuntu-latest
    steps:
      - name: Capture Vercel preview URL
        id: waitFor200
        uses: patrickedqvist/wait-for-vercel-preview@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 60
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        id: runCypress
        with:
          record: true
          parallel: true
          ci-build-id: "${{ github.sha }}-${{ github.workflow }}-${{ github.event_name }}"
          config: baseUrl=${{steps.waitFor200.outputs.url}}
        env:
          CYPRESS_RECORD_KEY: ${{ env.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: automerge
        if: ${{ steps.runCypress.outcome == 'success' && github.ref != 'refs/heads/master' }}
